### ISSUE TITLE
not work API

### ISSUE THREAD

**Issue by Vinchenz0** [pbojan/cryptocoins-desklet-windows#10]
Hallo / Привет
The api code does not work for me for 2 days, there are errors: (Fetch error) Unable to communicate with the server (ErrorCode = 12029) 

update version, the problem is not solved
Rainmeter v4.5.2
CryptoCoins v1.6
Thanks 
![Снимок](https://user-images.githubusercontent.com/90795429/133491215-fdec7b6d-904f-46f6-80b3-48c1a9c37d1b.JPG)

**Comment by pbojan** [comment]
Hello @Vinchenz0, did you add your API-KEY after the update? I cant see any issue on my side at the moment. 

You can debug the issue if you remove the `;` from the following 2 lines and then look for a file `WebParserDump.txt` and check the content. 
https://github.com/pbojan/cryptocoins-desklet-windows/blob/c1d9ee5d9b9b8de5b74c8a775c98688b83173e41/pbojan/%40Resources/CryptoCoins.ini#L44-L45
