### ISSUE TITLE
Catecoin

### ISSUE THREAD

**Issue by YushirohMurasakih** [pbojan/cryptocoins-desklet-windows#11]
ive been using this widget as my go to crypto ticker, but it seems like i am having problem when i put catecoin to a custom skin, at first it shows the cash tech coin but when i started to use the catecoin data currency id the widget does not show info about the crypto

**Comment by pbojan** [comment]
Hey @YushirohMurasakih, it seems that there are multiple Coins that have **CATE** as their symbol. To avoid this problem you can use the ID of CateCoin(9656) to specify exactly what coin e.g. 

> ; Instead of the CoinSymbol it is also possible to use the CoinID to specify the coin. Check the documentation how to get the CoinID for your currency
CoinID=9656

Here is my screenshot (if you want to add icon as well check the readme file):

![catecoin](https://user-images.githubusercontent.com/2048953/144715477-bbaa35d3-c678-40cc-91e4-56b973fbd939.png)

Hope this helps!
