### ISSUE TITLE
All the field values went crazy

### ISSUE THREAD

**Issue by Owsiana** [pbojan/cryptocoins-desklet-windows#12]
Something strange just happened. All the fields have crazy values as it is shown in the following picture:
https://iili.io/7UuPKN.png

BTW, please don't pay attention to colors and fonts. These have been modified slightly for my own needs.

**Comment by Owsiana** [comment]
Everything went back to normal. Looks like some temporary issues with the API.

**Comment by pbojan** [comment]
Hey @Owsiana, thanks for reporting it! Yes coinmarketcap had technical issues with their prices.
