### ISSUE TITLE
Feature Request: Refresh option

### ISSUE THREAD

**Issue by JSkier21** [pbojan/cryptocoins-desklet-windows#2]
I would like to suggest a refresh option from the menu on the desklet. Sometimes the tracker gets stuck, and won't refresh until I leave my DE, or re-enter the api key.

**Comment by pbojan** [comment]
Hey @JSkier21, are you using the Linux Mint Cinnamon Desklet? I like the idea and already updated the desklet to have a manual "Refresh" option on the right-click menu. It should be live in a few days and you will be able to update to the new desklet version. Cheers :+1:

**Comment by JSkier21** [comment]
Apologies, I should have mentioned on FP, I'm using ArchLinux, w/ cinnamon DE. Seems to get stuck after suspend and gets worse with longer uptime. Otherwise, overall, I like the desklet a lot 👍 

I appreciate the feature add, looking forward to the rt-click refresh option, thank you!
