### ISSUE TITLE
25 Minutes delay

### ISSUE THREAD

**Issue by pasambaires** [pbojan/cryptocoins-desklet-windows#3]
Is there any way to increase the refresh rate of the updates on prices?

**Comment by pbojan** [comment]
Hey @pasambaires, yes this is possible:

- right-click the skin and then select Edit Skin
- the config should open in your default editor and then find the UpdateTime
- Add different value for the **UpdateTime** in sec
- One API credit is used per refresh so be mindful about how many skins you have and how many credits you have

```
; The update time of the data on the widget in seconds. Default is 1800 sec (30 minutes).
; NOTE: Using lower value will use more resources on your computer and API credits.
UpdateTime=1800
```
