### ISSUE TITLE
Calculating/Display errors with tokens/coins that have a very low value

### ISSUE THREAD

**Issue by eponra** [pbojan/cryptocoins-desklet-windows#6]
If you add SAFEMOON to the coins/tokes you want to track, it displays the values not with the leading 5 zeros,
but like 4e-06, also if i add a calculation to the widget of my actual amount of tokens, the sum is wrong.

Here my way to display the actual amount of my coins/tokens:

`[MeasurePrice]
Measure=Calc
Formula=(0.11556 * MeasureCoinPriceRounded)
DynamicVariables=1

[MeterDisplayOverallPrice]
Meter=String
MeasureName=MeasurePrice
MeterStyle=StyleFont | StylePrice
X=100
Y=90
Text= %1 #Currency#` 

Another token that is displayed completely wrong is BONFIRE, which now sits at 0.000000x.
The actual price is shown as "0", and of course the calculation then displays "0".

My theory is, that the problem lies in the way the value is called in "Cryptocoins.ini", and then leads to the display/calculation error. But my knowledge of that all is not good enough to fix this issue by myself.

Greetings and thanks for the good work!

**Comment by pbojan** [comment]
Hey @eponra, thanks for the feedback and reporting the issue. It should be fixed now! You can download the [Helpers.lua](https://github.com/pbojan/cryptocoins-desklet-windows/blob/master/pbojan/%40Resources/scripts/Helpers.lua) and update it manually or wait for the next version release.

**Comment by eponra** [comment]
Many thanks for fixing this, and have a nice week!

Im waiting for the next version then!
